- deps/vg.proto
Someone came by with a question about what the offset in an Alignment's refpos really means. I dug through the code and found out that it means the Alignment's minimum position along the path.
> Document refpos semantics for Alignments

- include/vg/io/blocked_gzip_output_stream.hpp
- include/vg/io/registry.hpp
- src/blocked_gzip_input_stream.cpp
- src/message_iterator.cpp
Also makes a change to a protobuf call so that it works on libprotobuf-dev/bionic,now 3.0.0-9.1ubuntu1 amd64.
> make compilation work when we haven't used namespace std

- include/vg/io/message_emitter.hpp
- include/vg/io/message_iterator.hpp
- include/vg/io/protobuf_iterator.hpp
- include/vg/io/stream.hpp
- include/vg/io/vpkg.hpp
- src/message_emitter.cpp
- src/message_iterator.cpp
This PR lets libvgio work when you do `vg::io::VPKG::load_one<HandleGraph>(stream)`. It detects that a HandleGraph is not default constructible, so if nothing loadable as that type is found, the load will fail at runtime.
Right now, the load fails at compile time, because we can't call the default constructor of HandleGraph in the empty file case.
> Allow loading of non-default-constructible types like abstract base classes

- include/vg/io/stream.hpp
- src/message_iterator.cpp
With tag-only items being visible in the MessageIterator, we can now get into a situation where we allocate a batch but never put anything in it. The code to handle the final batch assumes it is nonempty.
I've wrapped it in an if check, so we only actually loop over it if any items are present.
Also, I fixed an int overflow warning, by just passing the biggest int.
> Handle empty final batches

- src/message_iterator.cpp
This was left over from some hacking I did earlier.
> correct overflow due to errant constant multiplication

- CMakeLists.txt
- include/vg/io/message_emitter.hpp
- include/vg/io/message_iterator.hpp
- include/vg/io/protobuf_emitter.hpp
- include/vg/io/protobuf_iterator.hpp
- include/vg/io/registry.hpp
- include/vg/io/stream.hpp
- include/vg/io/vpkg.hpp
- src/blocked_gzip_input_stream.cpp
- src/message_emitter.cpp
- src/message_iterator.cpp
- src/stream.cpp
- src/stream_multiplexer.cpp
This allows for VPKG to be compressed or uncompressed, and makes it uncompressed by default.
It required an htslib with https://github.com/samtools/htslib/pull/901 for random access in these uncompressed files to work correctly.
> Decompress vpkg

- include/vg/io/registry.hpp
- include/vg/io/vpkg.hpp
- src/blocked_gzip_input_stream.cpp
- src/registry.cpp
- src/vpkg.cpp
This adds a system for restricting bare loaders to certain magic number prefixes on their file streams, so that you can have any number of them for a type. It also lets you register bare loaders for base classes.
> Magic numbers

- CMakeLists.txt
I had a build of vg fail because Protobuf headers used by libvgio had lambda functions in them and -std=c++14 wasn't making it into libvgio's build. Since some Protobuf releases need a modern C++, I am making libvgio need a modern C++.
> Use C++14 standard

- include/vg/io/stream.hpp
This doesn't make a difference for me, but will hopefully help with https://github.com/vgteam/vg/issues/2522
> explicitly share batch size variable with omp

- include/vg/io/message_iterator.hpp
- include/vg/io/registry.hpp
- src/message_iterator.cpp
This allows tags to be sniffed from Protobuf-style streams like the BlockedGzipInputStream.
It also allows loaders to be registered separately from savers, and to be registered for multiple tags, in the Registry. This is useful for adding loaders that convert formats, where you don't necessarily want a corresponding saver.
> Sniff Proto Streams and Allow Multiple Loaders

- src/vpkg.cpp
This is the commit vg is currently pointing to; it ought to be merged to master. I had to tweak how sniffing works so it wouldn't get streams stuck in EOF.
> Don't EOF streams by sniffing

- README.md
Ryan has a multi-member non-blocked GZIP from GraphAligner, and we can't read it if not supplied with a sufficiently new htslib. We ensured that we had one in vg, but when we moved code over to this project that became the user's problem.
We should at least tell the user about it, even if we don't flatly refuse to build on old htslibs.
> Note that we need htslib 1.10 to avoid known bugs

- include/vg/io/message_emitter.hpp
- src/message_emitter.cpp
This is not particularly serious, but I get a ton of annoying clang warnings when compiling VG (one for every source file that has a transitive message_emitter.hpp include) about how the move constructor is implicitly deleted because `MAX_MESSAGE_SIZE` is const. I'm assuming that there won't be any issue making it const static like the equivalent variable for the `MessageIterator`.
> Make max emitter message size static to silence clang warnings

- CMakeLists.txt
We currently find Protobuf by two different methods, which for @jeizenga manages to find two different Protobufs.
This changes the CMake build system to use one method, and just guess the static library path based on the dynamic library path.
> Find Protobuf once and guess static lib

- deps/vg.proto
The extension consists of an edge between subpaths that is not required to respect adjacency in the graph, and that can also be associated with a score.
> Extend the schema for multipath alignments to accommodate splicing

- include/vg/io/alignment_io.hpp
- src/alignment_io.cpp
It's annoying, but node lengths are needed to go from GAF+cs cigar into Protobuf Alignment records. Otherwise, there's no way of knowing which edits go into which nodes.  This PR adds a a slightly more general interface to take the node information from callbacks instead of a graph.
> Add gaf interface that can use callbacks instead of graph

- include/vg/io/alignment_io.hpp
- src/alignment_io.cpp
When streaming in GAF, there are two steps
1) read a line of input and parse into a `GafRecord`
2) convert the `GafRecord` into a protobuf `Alignment`
The second step can be slow in practice, as a lot of graph queries are needed to get from a cs:cigar into an array of Edits.  Previously, the GAF input funcitons were doing both steps in series, then farming off batches of Alignments to be processed in parallel.  This PR changes it to do only step 1 in series, and pushes the GAF->GAM conversion into the parallel part, which drastically improves wall time in my `vg pack` tests.
> Parallelize gam conversion when streaming in gaf

- CMakeLists.txt
Currently libvgio builds fail on Catalina (maybe all cmake builds?) because handlegraph isn't listed as a dependency and so isn't built before vgio. This fixes https://github.com/vgteam/vg/issues/3014
> Explicit handlegraph dependency (fixes Mac build)

- include/vg/io/fdstream.hpp
- include/vg/io/vpkg.hpp
- src/vpkg.cpp
We can't sniff for magic numbers on standard input, because the standard library provides no way to unget the characters we sniff. This prevents libbdsg graphs being streamed from tool to tool without VPKG framing. But the VPKG framing prevents libbdsg from reading them, and especially prevents potential mmap-based acceleration for on-disk reads.
This enables libvgio to read non-VPKG-framed data from standard input, by adding a buffering stream wrapper when reading from standard input.
Problems with reading from named pipes probably still exist; we ought to consider detecting and wrapping them too.
We might want to experiment to find a fast buffer size on all platforms.
> Buffer standard input to allow putback

- deps/vg.proto
- src/alignment_io.cpp
Add an optional field to gaf that indicates whether a read was paired properly. This corresponds to an annotation in the Alignment called "proper_pair"
> Properly paired tag

- include/vg/io/gafkluge.hpp
This type of record isn't (yet) used by vg, so I guess this is why it never came up, but just found a bug when using gafkluge on minigraph output where path steps of the form `chr1:0-100` would end up with contig name `chr1:` instead of `chr1`
> Fix interval parsing bug in gafkluge

- include/vg/io/gafkluge.hpp
- src/alignment_io.cpp
Presently, only `cs` cigars are read, as they contain the insertion and subsitution sequences we've come to expect from GAM.  This updates the GAF parser to fall back on `cg` cigars if `cs` cigars aren't found.  There's less information (SNPs get glossed over, insertions sequences are filled with Ns), but the results can still be useful, ie for `vg pack`.
> Support cg cigars in GAF

- include/vg/io/gafkluge.hpp
(Stacks on #40)
A couple of bad habits of mine combined to hide a serious bug in GAF parsing:
1. passing end positions instead of lengths to the second parameter of `string::substr()`
2. forgetting that `stol()` silently ignores non-numeric trailing characters
The result is that a path  like`1>2>3>4>5` was getting parsed into steps with names like
`1`
`2>3`
`3>4>5` etc. where the strings get bigger as you go.  
Since `stol("3>4>5") = 3`, the results ended up looking fine for all vg-based testing.  It was only today seeing the quadratic memory needed to parse a chr8 path go past 300G did I realize something was wrong...
> Fix bad GAF parsing bug

- CMakeLists.txt
This makes the project better behaved when used via `add_subdirectory()`.
> Use our own source dir when a subdirectory

- CMakeLists.txt
I had a couple of issues to build libvgio on macOS Big Sur 11.5.2 and use it as a dependency in another project (i.e. handling transitive dependencies). This PR fixes all issues I encountered:
- CMake can detect OpenMP flags for GCC/Clang. So, it is only required to link targets with `OpenMP::OpenMP_CXX` and there is no need to set the flags manually. _Otherwise, the compiler complains that it cannot find `-lomp`. Also, the hard-coded paths where the libomp is supposed to be installed are not the same in all systems (I might have to change to `-L/opt/homebrew/lib` for example). In any case, why bother setting variables which will be handled by CMake anyway._
- Fix transitive dependencies for HTS and Jansson libraries by `target_link_directories` as CMake 3.13+ is available on most distros …
> Fix CMake build script

- include/vg/io/protobuf_iterator.hpp
- src/message_iterator.cpp
VG Mac tests started having errors like:
```
/Users/runner/work/vg/vg/deps/libvgio/include/vg/io/protobuf_iterator.hpp:274:76: error: too many arguments to function call, expected single argument 'total_bytes_limit', have 2 arguments
coded_stream.SetTotalBytesLimit(MessageIterator::MAX_MESSAGE_SIZE * 2, MessageIterator::MAX_MESSAGE_SIZE * 2);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/google/protobuf/io/coded_stream.h:406:3: note: 'SetTotalBytesLimit' declared here
void SetTotalBytesLimit(int total_bytes_limit);
```
The two-argument version of `SetTotalBytesLimit` was apparently deprecated and eventually removed. This should hopefully fix the issue.
> Use single-argument version of SetTotalBytesLimit

- include/vg/io/alignment_emitter.hpp
- include/vg/io/alignment_io.hpp
- include/vg/io/message_iterator.hpp
- src/alignment_emitter.cpp
- src/alignment_io.cpp
This came up in https://github.com/vgteam/vg/issues/3533, where giraffe was making a node mapping that contains only an insertion.  This triggered a bug in the roundtrip GAM->GAF->GAM where the softclip got left shifted to the preceding node (intentional) but the remaining mapping was left dangling on the GAM.  and becase we interpret no edits as a full mapping instead of 0-mapping in most of vg, this caused problems.  
Anyway, this PR adds and explicit check for this case in both directions.  And in both cases, the softclip will get shifted to the preceding node, and the node with the empty mapping removed from the path entirely.  
Stacks on #50. 
(To merge only once https://github.com/vgteam/vg/pull/3537 passes...)
> Disallow trailing softclip-only mappings in GAM<=>GAF conversion

- include/vg/io/message_iterator.hpp
The switch happened in the change between [3.5](https://github.com/protocolbuffers/protobuf/blob/v3.5.0/src/google/protobuf/io/coded_stream.h#L402) and [3.6](https://github.com/protocolbuffers/protobuf/blob/v3.6.0/src/google/protobuf/io/coded_stream.h#L385).  But since then, it's been consistently 1-parameter ex: [3.17.3](https://github.com/protocolbuffers/protobuf/blob/v3.17.3/src/google/protobuf/io/coded_stream.h#L400), [3.18.0](https://github.com/protocolbuffers/protobuf/blob/v3.18.0/src/google/protobuf/io/coded_stream.h#L401), [3.11.1](https://github.com/protocolbuffers/protobuf/blob/v3.11.1/src/google/protobuf/io/coded_stream.h#L392).  This PR hacks in a 1-parameter macro for versions < 3.6, which seems to allow compilation for all versions.  
Resolves #49 #43
> Support both 1- and 2-parameter versions of setTotalBytesLimit()

- include/vg/io/gafkluge.hpp
This is a bad bug that added an extra char to some step names, but vg (where all testing is done) never cared because the names were cast to ints and trailing characters ignored.
> Fix GAF parsing bug

- include/vg/io/fdstream.hpp
- include/vg/io/message_iterator.hpp
- src/message_iterator.cpp
@xchang1 was reporting some distance index files not being loadable after serialization.
I added some machinery to inspect the offending VPKG-encapsulated files and found that there was nothing wrong with the encapsulation; it was encapsulating a truncated underlying stream at about 2 GB.
I added a test to vg to try and transform a 3 GB block through `with_function_calling_stream`, and found that it did not work.
The underlying problem seems to be in the `fdstream` code we borrowed; the `fdostream`'s `fdoutbuf` doesn't guard against partial writes. The underlying `::write()` on an FD can succeed while only writing part of the data (and it turns out it does do that for us when we try and send more than 2 GB at a time), but the `xsputn()` method on the streambuf is deemed to fave failed if …
> Support big writes through stream encapsulation

- CMakeLists.txt
- include/vg/io/fdstream.hpp
- include/vg/io/registry.hpp
- src/alignment_io.cpp
Unmapped reads are missing the fragment_prev/fragment_next tags in GAF. It causes errors when surjecting pairs of reads when one or both are unmapped (from GAF).
There is an open issue on vg: https://github.com/vgteam/vg/issues/3711. I also encountered the bug when testing the new HPRC Giraffe-DV WDLs which attempt to use GBZ and GAF as much as possible.
I think it should work now. At least it fixes the problem in the tiny test graph.
> Write fp/fn tags for unmapped reads too in GAF

- CMakeLists.txt
This changes how we find Protobuf to use Protobuf's own bundled CMake config, instead of `FindProtobuf.cmake`, because Homebrew is packaging a Protobuf that can't be found by the `FindProtobuf.cmake` in Homebrew's CMake.
This also lets us send in a C++ standard version, so that we can deal with Homebrew shipping a Protobuf where the headers can't be included on C++ < 17.
> Support Protobuf's Abseil dependency being released befroe CMake supports it

- include/vg/io/alignment_io.hpp
- src/alignment_io.cpp
GAF alignment end positions (and consequently block lengths) seem to have not been at all correct for a long time.
> Add debug logging and fix GAF end computation

- CMakeLists.txt
This uses the installed libhandlegraph if it can be found, using https://github.com/vgteam/libhandlegraph/pull/95
If it can't, we fall back to building the submodule.
> Use installed libhandlegraph if available

- README.md
- include/vg/io/alignment_emitter.hpp
- include/vg/io/alignment_io.hpp
- include/vg/io/basic_stream.hpp
- include/vg/io/edit.hpp
- src/alignment_emitter.cpp
- src/json2pb.cpp
- test.cpp
We really should use "" for internal-to-package references and <> for references to things like htslib.
I'm not *quite* changing over to relative paths for this, but maybe I should?
Also I'm updating libhandlegraph to avoid some warnings, and documenting the build on Mac so you can actually find OpenMP.
> Fix include references

- include/vg/io/blocked_gzip_input_stream.hpp
- include/vg/io/message_iterator.hpp
- include/vg/io/stream.hpp
- src/blocked_gzip_input_stream.cpp
- src/message_iterator.cpp
I noticed that our new cluster can deliver GAM files at about 1.5 GB/s, but gzip decompression runs at something like 40 MB/s.
This tells htslib to use 8 decompression threads whenever we want to do a parallel read through stream.hpp. This ought to make things like `vg filter` better able to keep actual work threads busy when reads are long and take a lot of decompressing.
I'm not doing any clever stuff to budget the threads out of the user-requested thread count, so the user is always going to get 8 decoding threads even if they ask for e.g. 1 or 2 threads for the vg run. It's possible this will cause trouble in cases like containers where CPU is actually constrained, but I don't think htslib will let the decompression get too far ahead of the processing.
> Use 8 decoding threads when reading BGZF files (GAM, etc.)

- include/vg/io/stream.hpp
- src/stream.cpp
This lets you pass a progress callback to `for_each()` and `for_each_parallel()`.
> Add support for progress reporting to the stream.hpp API

- include/vg/io/blocked_gzip_input_stream.hpp
- include/vg/io/message_iterator.hpp
- include/vg/io/protobuf_iterator.hpp
- include/vg/io/stream.hpp
- src/blocked_gzip_input_stream.cpp
- src/message_iterator.cpp
This revises the multithreaded BGZF decode so that you always set it up in the reader's constructor. It also fixes the progress reporting to not clash with the BGZF decoder's internal threads that are trying to read from the C++ stream, since it's not safe to tell the stream while that is happening.
> Fix multithreading and progress reporting together

- include/vg/io/blocked_gzip_input_stream.hpp
- include/vg/io/stream.hpp
- include/vg/io/stream_multiplexer.hpp
- src/blocked_gzip_input_stream.cpp
- src/stream_multiplexer.cpp
This adds error detection for failed writes in the stream multiplexer, and will fail if you try and open a BGZF file that is seekable and truncated.
This should give better results when it is possible you will run out of disk space when working with GAM files.
> Detect file truncation on write and on read

- include/vg/io/message_iterator.hpp
- include/vg/io/registry.hpp
- include/vg/io/stream.hpp
- src/json2pb.cpp
vg started failing Mac CI tests because the current Homebrew release of Protobuf had some breaking changes related to Protobuf API return types. See:
* https://github.com/vgteam/vg/actions/runs/16995911969/job/48186437774
* https://protobuf.dev/support/migration/#v30
This fixes libvgio so it can work with newer Protobuf versions. This mostly consists of copying things into `std::string`s, because we can't really do things like "replace STL containers with Abseil ones" and because we also need to keep working on older Protobuf versions that don't hand us views.
> Port to Protobuf 32
